apiVersion: v1
kind: Secret
metadata:
  name: notes-app-api-env
  namespace: notes-app
type: Opaque
stringData:
  POSTGRES_DB: app
  POSTGRES_USER: {{ POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ POSTGRES_PASSWORD }}
  POSTGRES_HOST: notes-app-db
  POSTGRES_PORT: "5432"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  REFRESH_TOKEN_EXPIRE_DAYS: "15"
  SECRET_KEY: {{ SECRET_KEY }}
