apiVersion: v1
kind: Secret
metadata:
  name: notes-app-db-env
  namespace: notes-app
type: Opaque
stringData:
  POSTGRES_DB: app
  POSTGRES_USER: {{ POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ POSTGRES_PASSWORD }}
  POSTGRES_HOST: notes-app-db
  POSTGRES_PORT: "5432"
