apiVersion: v1
kind: Service
metadata:
  name: notes-app-frontend
  namespace: notes-app
spec:
  selector:
    app: notes-app-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
