"""Added User fkey to Note

Revision ID: 214d16db7d54
Revises: 7e1e9b40e0c9
Create Date: 2025-04-26 15:15:57.871962

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "214d16db7d54"
down_revision: Union[str, None] = "7e1e9b40e0c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("note", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "note", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "note", type_="foreignkey")
    op.drop_column("note", "user_id")
    # ### end Alembic commands ###
