name: CI

on: [push, pull_request]

jobs:
  ci:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_BACKEND: ghcr.io/${{ github.repository_owner }}/notes-app-api
      IMAGE_FRONTEND: ghcr.io/${{ github.repository_owner }}/notes-app-frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set TAG from commit hash
        run: echo "TAG=${GITHUB_SHA::8}" | tee -a $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check linting and formatting
        run: |
          ruff format --diff
          ruff check --select I
      - run: docker compose down -v --remove-orphans
      - name: Start containers
        run: docker compose up -d --build --wait notes-app-db notes-app-api
      - name: Backend healthcheck
        run: |
          for i in {1..5}; do
            if curl -f http://localhost:8000/api/v1/utils/ping; then
              echo "Backend healthcheck OK!"
              exit 0
            fi
            echo "Backend not healthy, retrying in 2s..."
            sleep 2
          done
          echo "Backend healthcheck FAILED!"
          exit 1
      - name: Run backend tests
        run: |
          export RUN_MODE=test
          python3 -m pytest
      - name: Stop containers
        if: always()
        run: docker compose down -v --remove-orphans
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push backend image
        run: |
          docker build -t $IMAGE_BACKEND:$TAG .
          docker push $IMAGE_BACKEND:$TAG
      - name: Build and push frontend image
        run: |
          cd frontend
          docker build -t $IMAGE_FRONTEND:$TAG .
          docker push $IMAGE_FRONTEND:$TAG
