name: CI

on: [push, pull_request]

jobs:
  ci:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check linting and formatting
      run: |
        ruff format --diff
        ruff check --select I
    - run: docker compose down -v --remove-orphans
    - name: Start containers
      run: docker compose up -d --build --wait notes-app-db notes-app-api
    - name: Backend healthcheck
      run: |
        for i in {1..5}; do
          if curl -f http://localhost:8000/api/v1/utils/ping; then
            echo "Backend healthcheck OK!"
            exit 0
          fi
          echo "Backend not healthy, retrying in 2s..."
          sleep 2
        done
        echo "Backend healthcheck FAILED!"
        exit 1
    - name: Run backend tests
      run: |
        python3 -m pytest
    - name: Stop containers
      if: always()
      run: docker compose down -v --remove-orphans
